#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
app_home_rest:
    path: /home/rest
    controller: App\Controller\HomeController::rest